### ISSUE TITLE
Usage document needed

### ISSUE THREAD

**Issue by itewqq** [aadomn/giftcofb_adomnicai#1]
Hi there,

We have been asked by NIST to evaluate your algorithm, could you please tell us how you use the implementation with masks here?

It does not appear that there is any crossover between the part that generates the mask and the main part of the encryption. It would be helpful to give some examples, thank you!

**Comment by aadomn** [comment]
Hi!

I have to admit that my documentation is quite succinct, so please do not hesitate to reach me out so that I can answer your questions and update the document accordingly.

Regarding the usage of the implementation, my understanding of [the call for protected implementions](https://cryptography.gmu.edu/athena/LWC/Call_for_Protected_Software_Implementations.pdf) is as follows:

1. First call `generate shares encrypt()` to generate the masks.
2. Then call `crypto aead encrypt shared()` to encrypt/authenticate the input.
3. Finally call `combine shares encrypt()` to get the resulting ciphertext/authentication tag without masking.

I should have time this week-end to update the document in order to include a sample main program, I will notice you when done.

Cheers,

**Comment by aadomn** [comment]
Hi @itewqq

I added an example in the documentation on how to use the API proposed in the call for software protected implementations (according to my understanding).
Hope this help! If not please do not hesitate to come back to me.

Cheers,

**Comment by itewqq** [comment]
@aadomn  I see, thank you very much! 🤝
